import e from"axios";import{AIODate as i,Storage as t}from"aio-utils";import o from"aio-popup";import r from"jquery";import"./index.css";function _defineProperty(e,i,t){return(i=_toPropertyKey(i))in e?Object.defineProperty(e,i,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[i]=t,e}function _toPropertyKey(e){var i=_toPrimitive(e,"string");return"symbol"==typeof i?i:i+""}function _toPrimitive(e,i){if("object"!=typeof e||!e)return e;var t=e[Symbol.toPrimitive];if(void 0!==t){var o=t.call(e,i||"default");if("object"!=typeof o)return o;throw TypeError("@@toPrimitive must return a primitive value.")}return("string"===i?String:Number)(e)}export default class s{constructor(s){_defineProperty(this,"storage",void 0),_defineProperty(this,"fn",void 0),_defineProperty(this,"getAppState",void 0),_defineProperty(this,"setStorage",void 0),_defineProperty(this,"getStorage",void 0),_defineProperty(this,"removeStorage",void 0),_defineProperty(this,"setToken",void 0),_defineProperty(this,"getLoading",void 0),_defineProperty(this,"handleLoading",void 0),_defineProperty(this,"responseToResult",void 0),_defineProperty(this,"request",void 0),_defineProperty(this,"addAlert",void 0),_defineProperty(this,"handleCacheVersions",void 0),_defineProperty(this,"showErrorMessage",void 0),_defineProperty(this,"showSuccessMessage",void 0),_defineProperty(this,"dateToString",void 0),_defineProperty(this,"dateToNumber",void 0),_defineProperty(this,"dateToArray",void 0),_defineProperty(this,"DATE",void 0);let{id:n,getAppState:a=()=>{},baseUrl:d,token:l,loader:c,apis:h,mock:v={},lang:g="en"}=s,u=new t(n);for(let f in this.storage=u,this.DATE=new i,this.getAppState=a,this.setStorage=(e,i)=>u.save(e,i),this.getStorage=(e,i)=>u.load(e,i),this.removeStorage=e=>u.remove(e),this.setToken=i=>{let t=i||s.token;t&&(e.defaults.headers.common.Authorization=`Bearer ${t}`)},this.addAlert=e=>{let{type:i,text:t,subtext:r,message:s}=e,{time:n,type:a="alert"}=s;"alert"===(a=a||"alert")?new o().addAlert({type:i,text:t,subtext:r,time:n}):new o().addSnackebar({type:i,text:t,subtext:r,time:n})},this.dateToString=(e,i="{year}/{month}/{day}")=>this.DATE.getDateByPattern(e,i),this.dateToNumber=e=>this.DATE.getTime(e),this.dateToArray=(e,i)=>this.DATE.convertToArray(e,i),this.getLoading=e=>(console.log(`aio-service show loading by ${e}`),`
              <div class="aio-service-loading" id="aio-service-${e}">
                <div class="aio-service-loading-0">
                  <div class="aio-service-loading-1">
                    <div class="aio-service-loading-2" style="animation: 1s ease-in-out 0.0s infinite normal none running aioserviceloading;"></div>
                    <div class="aio-service-loading-2" style="animation: 1s ease-in-out 0.1s infinite normal none running aioserviceloading;"></div>
                    <div class="aio-service-loading-2" style="animation: 1s ease-in-out 0.2s infinite normal none running aioserviceloading;"></div>
                    <div class="aio-service-loading-2" style="animation: 1s ease-in-out 0.3s infinite normal none running aioserviceloading;"></div>
                    <div class="aio-service-loading-2" style="animation: 1s ease-in-out 0.4s infinite normal none running aioserviceloading;"></div>
                  </div>
                </div>
              </div>
            `),this.handleLoading=(e,i,t)=>{let{loading:o=!0,loadingParent:s="body"}=t;if(o){if(e){let n=c?`<div class="aio-service-loading" id="aio-service-${i}">${c()}</div>`:this.getLoading(i);r(s).append(n)}else{let a=r("#aio-service-"+i);a.length||(a=r(".aio-service-loading")),a.remove()}}},this.handleCacheVersions=e=>{let i={};for(let t in e)i[t]=0;let o=this.getStorage("storedCacheVersions",i),r={};for(let s in e)void 0!==o[s]&&(o[s]!==e[s]?(r[s]=!0,this.removeStorage(s)):r[s]=!1);return this.setStorage("storedCacheVersions",e),r},this.showErrorMessage=e=>{let{result:i,message:t,description:o}=e;if(!1===t.error)return;let r;r="string"==typeof t.error?t.error:"fa"===g?`${o} با خطا روبرو شد`:`An error was occured in ${o}`,this.addAlert({type:"error",text:r,subtext:i,message:t})},this.showSuccessMessage=e=>{let{result:i,message:t,description:o}=e;if(!t.success)return;let r="function"==typeof t.success?t.success(i):t.success;!0===r&&(r=""),this.addAlert({type:"success",text:"fa"===g?`${o} با موفقیت انجام شد`:`${o} was successfull`,subtext:r,message:t})},this.responseToResult=async i=>{let{url:t,method:o,body:r,getResult:n,config:a={}}=i,{onCatch:d=s.onCatch,getError:l=s.getError}=a;try{let c=await e[o](t,void 0!==r?r:void 0);if(c){let h=l?l(c,a):void 0;if("string"==typeof h)return h}return n(c)}catch(v){let g;try{g=d?d(v,a):void 0}catch(u){g=u.message||u.Message}return g||(g=v.message||v.Message),console.log(v),g}},this.request=async e=>{let{id:i,config:t={},mockResult:o,parameter:r}=e;if(o&&"function"==typeof v[i]){this.handleLoading(!0,i,t);let s=await v[i](r);return this.handleLoading(!1,i,t),t.onSuccess&&t.onSuccess(s),s}let{onError:n,onSuccess:a,errorResult:d,cache:l,message:c={},description:h=i,token:g}=t;if(l){let u=this.storage.load(l.name,void 0,l.time);if(void 0!==u)return u}this.setToken(g),this.handleLoading(!0,i,t);let f=await this.responseToResult(e);return h="function"==typeof h?h(r):h,"string"==typeof f?(this.showErrorMessage({result:f,message:c,description:h}),n&&n(f),f=d):(this.showSuccessMessage({result:f,message:c,description:h}),void 0===f&&(f=d),l&&this.storage.save(l.name,f),a&&a(f)),this.handleLoading(!1,i,t),f},this.fn={},h)this.fn[f]=(e,i)=>{let t=h[f],{description:o=t.description,message:r=t.message,loading:s=t.loading,loadingParent:n=t.loadingParent,token:a=t.token,onError:l=t.onError,onSuccess:c=t.onSuccess,onCatch:v=t.onCatch,getError:g=t.getError,errorResult:u=t.errorResult,cache:p=t.cache,mockResult:y}=i||{},{getBody:m}=t,$={description:o,message:r,loading:s,loadingParent:n,token:a,onError:l,onSuccess:c,onCatch:v,getError:g,errorResult:u,cache:p},P="function"==typeof m?m(e):void 0,S="function"==typeof t.getUrl?t.getUrl(d,e):"",T="function"==typeof t.getResult?t.getResult:()=>{},w=!!t.mockResult||!!y;return this.request({parameter:e,config:$,mockResult:w,method:t.method?t.method:"post",body:P,url:S,id:f,getResult:T})}}};