let model = [
    {
        "name": "hot",
        "gender": "female",
        "age": 44,
        "date": "2021/9/2",
    },
    {
        "name": "save",
        "gender": "female",
        "age": 26,
        "date": "2021/1/21",
    },
    {
        "name": "frame",
        "gender": "female",
        "age": 43,
        "date": "2020/10/25",
    },
    {
        "name": "may",
        "gender": "male",
        "age": 22,
        "date": "2020/5/1",
    },
    {
        "name": "rain",
        "gender": "female",
        "age": 26,
        "date": "2021/9/3",
    },
    {
        "name": "gulf",
        "gender": "female",
        "age": 49,
        "date": "2021/5/5",
    },
    {
        "name": "total",
        "gender": "female",
        "age": 44,
        "date": "2021/6/12",
    },
    {
        "name": "gasoline",
        "gender": "male",
        "age": 47,
        "date": "2021/2/16",
    },
    {
        "name": "air",
        "gender": "male",
        "age": 57,
        "date": "2021/11/12",
    },
    {
        "name": "gather",
        "gender": "female",
        "age": 48,
        "date": "2020/6/27",
    },
    {
        "name": "hall",
        "gender": "female",
        "age": 34,
        "date": "2020/4/11",
    },
    {
        "name": "dried",
        "gender": "male",
        "age": 19,
        "date": "2020/6/26",
    },
    {
        "name": "natural",
        "gender": "male",
        "age": 32,
        "date": "2021/3/16",
    },
    {
        "name": "image",
        "gender": "male",
        "age": 23,
        "date": "2021/8/9",
    },
    {
        "name": "species",
        "gender": "male",
        "age": 18,
        "date": "2020/4/1",
    },
    {
        "name": "won",
        "gender": "female",
        "age": 22,
        "date": "2021/10/19",
    },
    {
        "name": "closely",
        "gender": "female",
        "age": 50,
        "date": "2021/2/1",
    },
    {
        "name": "dry",
        "gender": "female",
        "age": 49,
        "date": "2021/5/13",
    },
    {
        "name": "camera",
        "gender": "male",
        "age": 41,
        "date": "2020/8/2",
    },
    {
        "name": "gather",
        "gender": "female",
        "age": 25,
        "date": "2020/3/16",
    },
    {
        "name": "class",
        "gender": "male",
        "age": 37,
        "date": "2021/7/5",
    },
    {
        "name": "equally",
        "gender": "female",
        "age": 19,
        "date": "2021/5/16",
    },
    {
        "name": "bring",
        "gender": "male",
        "age": 37,
        "date": "2020/3/29",
    },
    {
        "name": "declared",
        "gender": "male",
        "age": 31,
        "date": "2021/4/16",
    },
    {
        "name": "sitting",
        "gender": "female",
        "age": 23,
        "date": "2021/3/17",
    },
    {
        "name": "won",
        "gender": "female",
        "age": 30,
        "date": "2020/2/23",
    },
    {
        "name": "importance",
        "gender": "male",
        "age": 53,
        "date": "2021/10/28",
    },
    {
        "name": "aside",
        "gender": "male",
        "age": 18,
        "date": "2021/6/10",
    },
    {
        "name": "please",
        "gender": "male",
        "age": 57,
        "date": "2021/10/15",
    },
    {
        "name": "pond",
        "gender": "female",
        "age": 56,
        "date": "2021/8/4",
    },
    {
        "name": "root",
        "gender": "female",
        "age": 24,
        "date": "2020/3/5",
    },
    {
        "name": "lion",
        "gender": "female",
        "age": 25,
        "date": "2021/9/29",
    },
    {
        "name": "specific",
        "gender": "male",
        "age": 21,
        "date": "2020/2/19",
    },
    {
        "name": "plates",
        "gender": "male",
        "age": 29,
        "date": "2021/4/12",
    },
    {
        "name": "process",
        "gender": "female",
        "age": 30,
        "date": "2020/6/4",
    },
    {
        "name": "boat",
        "gender": "male",
        "age": 45,
        "date": "2021/4/20",
    },
    {
        "name": "recent",
        "gender": "female",
        "age": 47,
        "date": "2020/9/28",
    },
    {
        "name": "three",
        "gender": "male",
        "age": 60,
        "date": "2020/11/10",
    },
    {
        "name": "fourth",
        "gender": "female",
        "age": 22,
        "date": "2020/5/3",
    },
    {
        "name": "dish",
        "gender": "male",
        "age": 60,
        "date": "2021/5/29",
    },
    {
        "name": "fog",
        "gender": "male",
        "age": 49,
        "date": "2021/3/9",
    },
    {
        "name": "sing",
        "gender": "male",
        "age": 57,
        "date": "2021/12/1",
    },
    {
        "name": "share",
        "gender": "female",
        "age": 29,
        "date": "2021/3/2",
    },
    {
        "name": "strike",
        "gender": "female",
        "age": 59,
        "date": "2022/1/3",
    },
    {
        "name": "bet",
        "gender": "male",
        "age": 24,
        "date": "2022/1/17",
    },
    {
        "name": "fifteen",
        "gender": "male",
        "age": 23,
        "date": "2021/11/20",
    },
    {
        "name": "spent",
        "gender": "male",
        "age": 29,
        "date": "2021/5/15",
    },
    {
        "name": "silence",
        "gender": "female",
        "age": 50,
        "date": "2021/3/15",
    },
    {
        "name": "simplest",
        "gender": "female",
        "age": 29,
        "date": "2021/5/13",
    },
    {
        "name": "happened",
        "gender": "female",
        "age": 30,
        "date": "2021/11/1",
    },
    {
        "name": "planning",
        "gender": "male",
        "age": 44,
        "date": "2022/1/8",
    },
    {
        "name": "discovery",
        "gender": "female",
        "age": 21,
        "date": "2021/1/14",
    },
    {
        "name": "improve",
        "gender": "male",
        "age": 57,
        "date": "2021/12/20",
    },
    {
        "name": "own",
        "gender": "female",
        "age": 27,
        "date": "2021/2/9",
    },
    {
        "name": "egg",
        "gender": "male",
        "age": 54,
        "date": "2020/2/1",
    },
    {
        "name": "realize",
        "gender": "female",
        "age": 60,
        "date": "2021/3/4",
    },
    {
        "name": "death",
        "gender": "female",
        "age": 25,
        "date": "2021/7/28",
    },
    {
        "name": "easier",
        "gender": "male",
        "age": 44,
        "date": "2020/4/5",
    },
    {
        "name": "west",
        "gender": "female",
        "age": 21,
        "date": "2021/2/16",
    },
    {
        "name": "establish",
        "gender": "female",
        "age": 54,
        "date": "2021/6/11",
    },
    {
        "name": "maybe",
        "gender": "male",
        "age": 24,
        "date": "2021/4/27",
    },
    {
        "name": "future",
        "gender": "male",
        "age": 26,
        "date": "2021/9/21",
    },
    {
        "name": "tip",
        "gender": "male",
        "age": 50,
        "date": "2021/6/26",
    },
    {
        "name": "nose",
        "gender": "male",
        "age": 23,
        "date": "2020/5/13",
    },
    {
        "name": "tip",
        "gender": "female",
        "age": 53,
        "date": "2021/3/14",
    },
    {
        "name": "pay",
        "gender": "female",
        "age": 50,
        "date": "2021/2/17",
    },
    {
        "name": "carefully",
        "gender": "female",
        "age": 34,
        "date": "2020/5/25",
    },
    {
        "name": "line",
        "gender": "male",
        "age": 37,
        "date": "2021/8/28",
    },
    {
        "name": "castle",
        "gender": "female",
        "age": 43,
        "date": "2021/12/13",
    },
    {
        "name": "harbor",
        "gender": "male",
        "age": 27,
        "date": "2021/5/9",
    },
    {
        "name": "make",
        "gender": "male",
        "age": 22,
        "date": "2021/11/14",
    },
    {
        "name": "been",
        "gender": "female",
        "age": 57,
        "date": "2020/5/18",
    },
    {
        "name": "chest",
        "gender": "male",
        "age": 38,
        "date": "2020/10/3",
    },
    {
        "name": "himself",
        "gender": "male",
        "age": 38,
        "date": "2021/9/21",
    },
    {
        "name": "hung",
        "gender": "male",
        "age": 45,
        "date": "2021/1/3",
    },
    {
        "name": "wait",
        "gender": "female",
        "age": 30,
        "date": "2020/6/6",
    },
    {
        "name": "circus",
        "gender": "female",
        "age": 58,
        "date": "2020/4/11",
    },
    {
        "name": "more",
        "gender": "male",
        "age": 50,
        "date": "2021/1/5",
    },
    {
        "name": "wrong",
        "gender": "male",
        "age": 55,
        "date": "2021/12/20",
    },
    {
        "name": "pet",
        "gender": "female",
        "age": 19,
        "date": "2020/6/3",
    },
    {
        "name": "nearest",
        "gender": "female",
        "age": 53,
        "date": "2021/2/19",
    },
    {
        "name": "rabbit",
        "gender": "female",
        "age": 45,
        "date": "2021/8/1",
    },
    {
        "name": "yet",
        "gender": "female",
        "age": 18,
        "date": "2020/6/25",
    },
    {
        "name": "given",
        "gender": "female",
        "age": 58,
        "date": "2022/1/13",
    },
    {
        "name": "nuts",
        "gender": "female",
        "age": 45,
        "date": "2021/12/1",
    },
    {
        "name": "suppose",
        "gender": "female",
        "age": 25,
        "date": "2021/7/31",
    },
    {
        "name": "coffee",
        "gender": "male",
        "age": 20,
        "date": "2020/3/5",
    },
    {
        "name": "applied",
        "gender": "male",
        "age": 51,
        "date": "2020/6/20",
    },
    {
        "name": "cotton",
        "gender": "female",
        "age": 31,
        "date": "2020/4/25",
    },
    {
        "name": "move",
        "gender": "male",
        "age": 60,
        "date": "2021/6/13",
    },
    {
        "name": "curious",
        "gender": "male",
        "age": 35,
        "date": "2020/8/23",
    },
    {
        "name": "studied",
        "gender": "female",
        "age": 41,
        "date": "2021/2/23",
    },
    {
        "name": "shut",
        "gender": "female",
        "age": 36,
        "date": "2021/12/11",
    },
    {
        "name": "gently",
        "gender": "female",
        "age": 25,
        "date": "2020/6/5",
    },
    {
        "name": "subject",
        "gender": "male",
        "age": 19,
        "date": "2020/8/8",
    },
    {
        "name": "fifty",
        "gender": "male",
        "age": 54,
        "date": "2021/11/16",
    },
    {
        "name": "tears",
        "gender": "male",
        "age": 47,
        "date": "2021/5/29",
    },
    {
        "name": "generally",
        "gender": "female",
        "age": 60,
        "date": "2020/8/30",
    },
    {
        "name": "related",
        "gender": "male",
        "age": 57,
        "date": "2021/12/11",
    },
    {
        "name": "saved",
        "gender": "female",
        "age": 58,
        "date": "2020/7/1",
    }
]


export default model;